# Generated by Django 4.2.7 on 2023-12-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='conent',
            new_name='content',
        ),
    ]
