# Generated by Django 4.2.7 on 2023-12-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_delete_messages_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sended_on', models.DateTimeField(auto_now=True)),
                ('recieved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by', to=settings.AUTH_USER_MODEL)),
                ('sended_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sended_on'],
            },
        ),
    ]
