# Generated by Django 4.2.7 on 2023-12-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
