# Generated by Django 4.2.7 on 2023-12-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
