# Generated by Django 4.2.7 on 2023-12-05 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_alter_thread_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sended_on', models.DateTimeField(auto_now=True)),
                ('first_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thr_first_prsn', to=settings.AUTH_USER_MODEL)),
                ('second_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thr_sec_prsn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sended_on'],
                'unique_together': {('first_person', 'second_person')},
            },
        ),
    ]
