# Generated by Django 4.2.7 on 2023-12-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
