# Generated by Django 4.2.7 on 2023-12-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_user_chatmessage_sended_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
